// ============================================================
// devtools.js —— 调试导出（window.FTT，替代 V1 的 window.__FTT）
// 约定：只读快照 + 少量探针函数；不暴露写数据能力（避免误操作）。
// ============================================================
import { VERSION, DATA_VERSION, MODULE_NAME, DIMENSIONS, HOST_EVENTS } from './core/constants.js';
import { hasHost, probeCapabilities, currentCharScope } from './host/st-api.js';
import { interceptorStats } from './host/interceptor.js';
import { readInject, injectAvailable } from './host/inject.js';
import { getSettings } from './adapters/settings.js';
import { statusText } from './ui/commands.js';
import { readUpdateState } from './adapters/update-state.js';
import { updateStatusText, hasUpdate, updateConfig } from './host/update.js';

export function buildSnapshot(extra) {
    const probe = hasHost() ? probeCapabilities() : { need: {}, missing: ['host'], ok: false };
    return {
        name: 'FTT记忆组件 V2',
        version: VERSION,
        dataVersion: DATA_VERSION,
        moduleName: MODULE_NAME,
        host: hasHost(),
        scope: currentCharScope(),
        probe,
        interceptor: interceptorStats(),
        inject: { available: injectAvailable(), key: MODULE_NAME, length: readInject().length },
        settings: getSettings(),
        update: { config: updateConfig(), state: readUpdateState(), status: updateStatusText(), hasUpdate: hasUpdate() },
        dimensions: DIMENSIONS.map(d => d.kind),
        hostEvents: HOST_EVENTS.slice(),
        status: statusText(Object.assign({ host: hasHost(), probe, interceptor: interceptorStats() }, extra || {})),
    };
}

/** 挂到 window.FTT（返回快照；不覆盖已存在的同名对象则合并） */
export function installDevtools(hooks) {
    const snap = buildSnapshot();
    try {
        const w = globalThis;
        w.FTT = Object.assign({}, w.FTT || {}, {
            version: snap.version,
            dataVersion: snap.dataVersion,
            snapshot: () => buildSnapshot(),
            status: () => snap.status,
            probe: () => probeCapabilities(),
            interceptor: () => interceptorStats(),
            injectLength: () => readInject().length,
            update: () => buildSnapshot().update,
            // P2：V1 数据导入（默认干跑；apply:true 才写入）
            importV1: (opts) => (hooks && typeof hooks.importV1 === 'function' ? hooks.importV1(opts || {}) : Promise.resolve({ ok: false, reason: 'no-hook' })),
            importStatus: () => (hooks && typeof hooks.importStatus === 'function' ? hooks.importStatus() : null),
            // P4：提取（AI 摘要）入口
            analyze: (opts) => (hooks && typeof hooks.extract === 'function' ? hooks.extract(opts || {}) : Promise.resolve({ ok: false, reason: 'no-hook' })),
            pendingFloors: (opts) => (hooks && typeof hooks.pendingFloors === 'function' ? hooks.pendingFloors(opts || {}) : []),
            extractStatus: () => (hooks && typeof hooks.extractStatus === 'function' ? hooks.extractStatus() : null),
            i18n: () => (hooks && typeof hooks.i18n === 'function' ? hooks.i18n() : null),
            folderInfo: () => (hooks && typeof hooks.folderInfo === 'function' ? hooks.folderInfo() : null),
            // 可见性诊断（用户报「装上了但看不到面板」时的第一现场）
            panelInfo: () => (hooks && typeof hooks.panelInfo === 'function' ? hooks.panelInfo() : null),
            menuInfo: () => (hooks && typeof hooks.menuInfo === 'function' ? hooks.menuInfo() : null),
            forceMount: () => (hooks && typeof hooks.forceMountPanel === 'function' ? hooks.forceMountPanel() : Promise.resolve({ ok: false, reason: 'no-hook' })),
            floatingInfo: () => (hooks && typeof hooks.floatingInfo === 'function' ? hooks.floatingInfo() : null),
            openPanel: () => (hooks && typeof hooks.openPanelPopup === 'function' ? hooks.openPanelPopup() : Promise.resolve({ ok: false, reason: 'no-hook' })),
            ui: (tab) => (hooks && typeof hooks.openPanelPopup === 'function' ? hooks.openPanelPopup(tab) : Promise.resolve({ ok: false, reason: 'no-hook' })),
            popupInfo: () => (hooks && typeof hooks.popupInfo === 'function' ? hooks.popupInfo() : null),
            panelInfo: () => (hooks && typeof hooks.v1PanelInfo === 'function' ? hooks.v1PanelInfo() : null),
            panelTabs: () => (hooks && typeof hooks.v1PanelTabs === 'function' ? hooks.v1PanelTabs() : []),
            injectNow: () => (hooks && typeof hooks.injectNow === 'function' ? hooks.injectNow() : Promise.resolve({ ok: false, reason: 'no-hook' })),
            summary: (opts) => (hooks && typeof hooks.summary === 'function' ? hooks.summary(opts || {}) : Promise.resolve({ ok: false, reason: 'no-hook' })),
            abort: () => (hooks && typeof hooks.abort === 'function' ? hooks.abort() : { ok: false, reason: 'no-hook' }),
            clearFloors: () => (hooks && typeof hooks.clearFloors === 'function' ? hooks.clearFloors() : Promise.resolve({ ok: false, reason: 'no-hook' })),
            exportState: () => (hooks && typeof hooks.exportState === 'function' ? hooks.exportState() : ''),
            importState: (text) => (hooks && typeof hooks.importState === 'function' ? hooks.importState(text) : Promise.resolve({ ok: false, reason: 'no-hook' })),
            popupAction: (a, p) => (hooks && typeof hooks.popupAction === 'function' ? hooks.popupAction(a, p || {}) : Promise.resolve({ ok: false, reason: 'no-hook' })),
            // B7-2 跨端同步（与 V1 `FTT.*` 同名能力）
            syncStatus: () => (hooks && typeof hooks.syncStatus === 'function' ? hooks.syncStatus() : null),
            syncInfo: () => (hooks && typeof hooks.syncInfo === 'function' ? hooks.syncInfo() : null),
            syncNow: () => (hooks && typeof hooks.syncNow === 'function' ? hooks.syncNow() : Promise.resolve({ ok: false, reason: 'no-hook' })),
            syncRefresh: () => (hooks && typeof hooks.syncRefresh === 'function' ? hooks.syncRefresh() : Promise.resolve({ ok: false, reason: 'no-hook' })),
            syncVerify: () => (hooks && typeof hooks.syncVerify === 'function' ? hooks.syncVerify() : Promise.resolve({ ok: false, reason: 'no-hook' })),
            syncLog: () => (hooks && typeof hooks.syncLog === 'function' ? hooks.syncLog() : []),
            syncLogClear: () => (hooks && typeof hooks.syncLogClear === 'function' ? hooks.syncLogClear() : 0),
            syncLogMerge: () => (hooks && typeof hooks.syncLogMerge === 'function' ? hooks.syncLogMerge() : Promise.resolve({ ok: false, reason: 'no-hook' })),
            syncLogServerStatus: () => (hooks && typeof hooks.syncLogServerStatus === 'function' ? hooks.syncLogServerStatus() : null),
            syncLogPush: (rec) => (hooks && typeof hooks.syncLogPush === 'function' ? hooks.syncLogPush(rec || {}) : 0),
            syncSource: () => (hooks && typeof hooks.syncSource === 'function' ? hooks.syncSource() : ''),
            syncDropCache: () => (hooks && typeof hooks.syncDropCache === 'function' ? hooks.syncDropCache() : false),
            storageBootstrap: () => (hooks && typeof hooks.storageBootstrap === 'function' ? hooks.storageBootstrap() : Promise.resolve({ ok: false, reason: 'no-hook' })),
            // B9-d 条目瘦身 + gzip 传输（V1 `__FTT` 同名能力；纯函数/异步压缩，均为只读或幂等）
            slimEntryForStorage: (cat, it) => (hooks && typeof hooks.slimEntryForStorage === 'function' ? hooks.slimEntryForStorage(cat, it) : null),
            hydrateSlimEntry: (cat, it) => (hooks && typeof hooks.hydrateSlimEntry === 'function' ? hooks.hydrateSlimEntry(cat, it) : null),
            slimDataForStorage: (data, opts) => (hooks && typeof hooks.slimDataForStorage === 'function' ? hooks.slimDataForStorage(data, opts || {}) : null),
            hydrateStorageData: (data) => (hooks && typeof hooks.hydrateStorageData === 'function' ? hooks.hydrateStorageData(data) : null),
            snapshotIndexFrom: (snaps) => (hooks && typeof hooks.snapshotIndexFrom === 'function' ? hooks.snapshotIndexFrom(snaps) : []),
            slimSnapshotStoreForStorage: (snaps) => (hooks && typeof hooks.slimSnapshotStoreForStorage === 'function' ? hooks.slimSnapshotStoreForStorage(snaps) : []),
            hydrateSnapshotStore: (snaps) => (hooks && typeof hooks.hydrateSnapshotStore === 'function' ? hooks.hydrateSnapshotStore(snaps) : []),
            slimFileEnvelope: (env, keepSnap) => (hooks && typeof hooks.slimFileEnvelope === 'function' ? hooks.slimFileEnvelope(env, keepSnap === true) : null),
            gzipToBase64: (text) => (hooks && typeof hooks.gzipToBase64 === 'function' ? hooks.gzipToBase64(text) : Promise.resolve({ ok: false, b64: '' })),
            gunzipFromBytes: (u8) => (hooks && typeof hooks.gunzipFromBytes === 'function' ? hooks.gunzipFromBytes(u8) : Promise.resolve(null)),
            bytesToBase64: (u8) => (hooks && typeof hooks.bytesToBase64 === 'function' ? hooks.bytesToBase64(u8) : ''),
            base64ToBytes: (b64) => (hooks && typeof hooks.base64ToBytes === 'function' ? hooks.base64ToBytes(b64) : null),
            isGzipBytes: (u8) => (hooks && typeof hooks.isGzipBytes === 'function' ? hooks.isGzipBytes(u8) : false),
            slimInfo: () => (hooks && typeof hooks.slimInfo === 'function' ? hooks.slimInfo() : null),
            // B9-d 跨端分歧处置（V1 `__FTT` 同名能力：crossComputeInfo / crossPendingGet / crossPendingClear /
            //   applyRemoteReplaceState / adoptRemoteEnvelope）
            //   注：`crossPendingClear` / `applyRemoteReplaceState` / `adoptRemoteEnvelope` 是 V1 `__FTT`
            //   同样导出的**有意为之**的写入口（改写本端 state），其余为只读查询。
            crossComputeInfo: (localData, remoteData, remoteTs) => (hooks && typeof hooks.crossComputeInfo === 'function' ? hooks.crossComputeInfo(localData, remoteData, remoteTs) : null),
            crossPendingGet: () => (hooks && typeof hooks.crossPendingGet === 'function' ? hooks.crossPendingGet() : null),
            crossPendingView: () => (hooks && typeof hooks.crossPendingView === 'function' ? hooks.crossPendingView() : null),
            crossPendingClear: () => (hooks && typeof hooks.crossPendingClear === 'function' ? hooks.crossPendingClear() : false),
            applyRemoteReplaceState: (env) => (hooks && typeof hooks.applyRemoteReplaceState === 'function' ? hooks.applyRemoteReplaceState(env) : false),
            adoptRemoteEnvelope: (env) => (hooks && typeof hooks.adoptRemoteEnvelope === 'function' ? hooks.adoptRemoteEnvelope(env) : false),
            // V1 `__FTT` 同名：自动对账入口 / 信封构造与校验
            crossPullPolicy: (label, opts) => (hooks && typeof hooks.crossPullPolicy === 'function' ? hooks.crossPullPolicy(label, opts || {}) : Promise.resolve({ skipped: 'no-hook' })),
            storageEnvelope: (data) => (hooks && typeof hooks.storageEnvelope === 'function' ? hooks.storageEnvelope(data) : null),
            storageHash: (payload) => (hooks && typeof hooks.storageHash === 'function' ? hooks.storageHash(payload) : ''),
            storageEnvValid: (env) => (hooks && typeof hooks.storageEnvValid === 'function' ? hooks.storageEnvValid(env) : false),
            // B8-1 剧情时钟（巡检 / 锚点 / 手工改写）
            clockUi: () => (hooks && typeof hooks.clockUi === 'function' ? hooks.clockUi() : null),
            clockPatrol: (opts) => (hooks && typeof hooks.clockPatrol === 'function' ? hooks.clockPatrol(opts || {}) : null),
            clockPatrolState: () => (hooks && typeof hooks.clockPatrolState === 'function' ? hooks.clockPatrolState() : null),
            clockPatrolAuto: () => (hooks && typeof hooks.clockPatrolAuto === 'function' ? hooks.clockPatrolAuto() : null),
            clockAnchor: () => (hooks && typeof hooks.clockAnchor === 'function' ? hooks.clockAnchor() : null),
            clockMajority: () => (hooks && typeof hooks.clockMajority === 'function' ? hooks.clockMajority() : null),
            clockScan: () => (hooks && typeof hooks.clockScan === 'function' ? hooks.clockScan() : null),
            clockManual: () => (hooks && typeof hooks.clockManual === 'function' ? hooks.clockManual() : null),
            clockManualSet: (input) => (hooks && typeof hooks.clockManualSet === 'function' ? hooks.clockManualSet(input || {}) : { ok: false, notes: ['no-hook'] }),
            clockManualClear: () => (hooks && typeof hooks.clockManualClear === 'function' ? hooks.clockManualClear() : false),
            // B8-2 剧情时钟自动提取
            clockResolve: (opts) => (hooks && typeof hooks.clockResolve === 'function' ? hooks.clockResolve(opts || {}) : null),
            clockExtractOnce: (opts) => (hooks && typeof hooks.clockExtractOnce === 'function' ? hooks.clockExtractOnce(opts || {}) : Promise.resolve(false)),
            clockExtractState: () => (hooks && typeof hooks.clockExtractState === 'function' ? hooks.clockExtractState() : null),
            clockExtractSchedule: () => (hooks && typeof hooks.clockExtractSchedule === 'function' ? hooks.clockExtractSchedule() : false),
            clockHeader: (text) => (hooks && typeof hooks.clockHeader === 'function' ? hooks.clockHeader(text) : null),
            clockExtractText: (text, prev) => (hooks && typeof hooks.clockExtractText === 'function' ? hooks.clockExtractText(text, prev || {}) : null),
            clockScene: () => (hooks && typeof hooks.clockScene === 'function' ? hooks.clockScene() : ''),
            // B8-3 时钟域 AI 管线
            clockRegexGen: (opts) => (hooks && typeof hooks.clockRegexGen === 'function' ? hooks.clockRegexGen(opts || {}) : Promise.resolve({ ok: false, reason: 'no-hook' })),
            clockRepair: (opts) => (hooks && typeof hooks.clockRepair === 'function' ? hooks.clockRepair(opts || {}) : Promise.resolve({ made: 0, error: 'no-hook' })),
            clockRepairPack: () => (hooks && typeof hooks.clockRepairPack === 'function' ? hooks.clockRepairPack() : null),
            // B8-4 内容弱化（NSFW）
            nsfwState: () => (hooks && typeof hooks.nsfwState === 'function' ? hooks.nsfwState() : null),
            nsfwSoften: (opts) => (hooks && typeof hooks.nsfwSoften === 'function' ? hooks.nsfwSoften(opts || {}) : Promise.resolve({ made: 0, error: 'no-hook' })),
            nsfwFixed: (opts) => (hooks && typeof hooks.nsfwFixed === 'function' ? hooks.nsfwFixed(opts || {}) : null),
            nsfwScan: (opts) => (hooks && typeof hooks.nsfwScan === 'function' ? hooks.nsfwScan(opts || {}) : null),
            nsfwHits: (text) => (hooks && typeof hooks.nsfwHits === 'function' ? hooks.nsfwHits(text) : []),
            nsfwApply: (text) => (hooks && typeof hooks.nsfwApply === 'function' ? hooks.nsfwApply(text) : null),
            nsfwKeywords: () => (hooks && typeof hooks.nsfwKeywords === 'function' ? hooks.nsfwKeywords() : []),
            nsfwRules: () => (hooks && typeof hooks.nsfwRules === 'function' ? hooks.nsfwRules() : []),
            nsfwKeywordAdd: (kw) => (hooks && typeof hooks.nsfwKeywordAdd === 'function' ? hooks.nsfwKeywordAdd(kw) : null),
            nsfwKeywordDelete: (i) => (hooks && typeof hooks.nsfwKeywordDelete === 'function' ? hooks.nsfwKeywordDelete(i) : null),
            nsfwRuleAdd: (f, t) => (hooks && typeof hooks.nsfwRuleAdd === 'function' ? hooks.nsfwRuleAdd(f, t) : null),
            nsfwRuleDelete: (i) => (hooks && typeof hooks.nsfwRuleDelete === 'function' ? hooks.nsfwRuleDelete(i) : null),
            nsfwKeywordReset: () => (hooks && typeof hooks.nsfwKeywordReset === 'function' ? hooks.nsfwKeywordReset() : null),
            nsfwRuleReset: () => (hooks && typeof hooks.nsfwRuleReset === 'function' ? hooks.nsfwRuleReset() : null),
            // B8-5 遗忘域
            forgetState: () => (hooks && typeof hooks.forgetState === 'function' ? hooks.forgetState() : null),
            forgetRunAll: (opts) => (hooks && typeof hooks.forgetRunAll === 'function' ? hooks.forgetRunAll(opts || {}) : Promise.resolve(null)),
            stateDecay: (opts) => (hooks && typeof hooks.stateDecay === 'function' ? hooks.stateDecay(opts || {}) : Promise.resolve(null)),
            memoryForget: (opts) => (hooks && typeof hooks.memoryForget === 'function' ? hooks.memoryForget(opts || {}) : Promise.resolve(null)),
            lowUseSweep: (opts) => (hooks && typeof hooks.lowUseSweep === 'function' ? hooks.lowUseSweep(opts || {}) : null),
            lowUseGate: (every) => (hooks && typeof hooks.lowUseGate === 'function' ? hooks.lowUseGate(every) : null),
            // B8-6a 修复管线（第 1 段 机械清理）
            repairMech: (opts) => (hooks && typeof hooks.repairMech === 'function' ? hooks.repairMech(opts || {}) : Promise.resolve(null)),
            repairReport: (o) => (hooks && typeof hooks.repairReport === 'function' ? hooks.repairReport(o || {}) : ''),
            repairLog: () => (hooks && typeof hooks.repairLog === 'function' ? hooks.repairLog() : []),
            repairTotal: () => (hooks && typeof hooks.repairTotal === 'function' ? hooks.repairTotal() : 0),
            repairGateTake: (reset) => (hooks && typeof hooks.repairGateTake === 'function' ? hooks.repairGateTake(!!reset) : null),
            repairGateDue: () => (hooks && typeof hooks.repairGateDue === 'function' ? hooks.repairGateDue() : true),
            repairBumpOp: () => (hooks && typeof hooks.repairBumpOp === 'function' ? hooks.repairBumpOp() : false),
            repairIsGarbage: (text, min) => (hooks && typeof hooks.repairIsGarbage === 'function' ? hooks.repairIsGarbage(text, min) : null),
            repairBanned: (text) => (hooks && typeof hooks.repairBanned === 'function' ? hooks.repairBanned(text) : []),
            repairDedupe: () => (hooks && typeof hooks.repairDedupe === 'function' ? hooks.repairDedupe() : null),
            repairPrune: () => (hooks && typeof hooks.repairPrune === 'function' ? hooks.repairPrune() : null),
            repairDecay: () => (hooks && typeof hooks.repairDecay === 'function' ? hooks.repairDecay() : Promise.resolve(null)),
            latestFloorHash: () => (hooks && typeof hooks.latestFloorHash === 'function' ? hooks.latestFloorHash() : ''),
            repairLogPush: (rec) => (hooks && typeof hooks.repairLogPush === 'function' ? hooks.repairLogPush(rec || {}) : 0),
            // B8-6b 修复第 2/3 段
            repair: (opts) => (hooks && typeof hooks.repair === 'function' ? hooks.repair(opts || {}) : Promise.resolve(null)),
            repairCandidates: (limit, stat) => (hooks && typeof hooks.repairCandidates === 'function' ? hooks.repairCandidates(limit, stat || {}) : []),
            repairPrompt: (cands) => (hooks && typeof hooks.repairPrompt === 'function' ? hooks.repairPrompt(cands) : null),
            repairApply: (delta, cands) => (hooks && typeof hooks.repairApply === 'function' ? hooks.repairApply(delta, cands) : null),
            repairDefect: (dim, e) => (hooks && typeof hooks.repairDefect === 'function' ? hooks.repairDefect(dim, e) : null),
            repairCorr: (dim, arr) => (hooks && typeof hooks.repairCorr === 'function' ? hooks.repairCorr(dim, arr) : null),
            repairTags: (entries) => (hooks && typeof hooks.repairTags === 'function' ? hooks.repairTags(entries) : []),
            repairJaccard: (a, b) => (hooks && typeof hooks.repairJaccard === 'function' ? hooks.repairJaccard(a, b) : 0),
            repairFailArmed: () => (hooks && typeof hooks.repairFailArmed === 'function' ? hooks.repairFailArmed() : false),
            // B8-7 传言演化（零 AI）与世界书单向镜像
            rumorEvolve: (opts) => (hooks && typeof hooks.rumorEvolve === 'function' ? hooks.rumorEvolve(opts || {}) : Promise.resolve(null)),
            rumorEvolveAuto: (opts) => (hooks && typeof hooks.rumorEvolveAuto === 'function' ? hooks.rumorEvolveAuto(opts || {}) : Promise.resolve(null)),
            rumorDecay: (opts) => (hooks && typeof hooks.rumorDecay === 'function' ? hooks.rumorDecay(opts || {}) : Promise.resolve(null)),
            clearRumors: () => (hooks && typeof hooks.clearRumors === 'function' ? hooks.clearRumors() : 0),
            rumorTick: () => (hooks && typeof hooks.rumorTick === 'function' ? hooks.rumorTick() : null),
            rumorEnabled: () => (hooks && typeof hooks.rumorEnabled === 'function' ? hooks.rumorEnabled() : false),
            rumorEveryRounds: () => (hooks && typeof hooks.rumorEveryRounds === 'function' ? hooks.rumorEveryRounds() : 5),
            rumorNeedRounds: () => (hooks && typeof hooks.rumorNeedRounds === 'function' ? hooks.rumorNeedRounds() : 2),
            rumorRoll: (seed) => (hooks && typeof hooks.rumorRoll === 'function' ? hooks.rumorRoll(seed) : 0),
            rumorDecayScore: (r) => (hooks && typeof hooks.rumorDecayScore === 'function' ? hooks.rumorDecayScore(r) : 0),
            rumorExpired: (r) => (hooks && typeof hooks.rumorExpired === 'function' ? hooks.rumorExpired(r) : false),
            rumorInjLine: (r) => (hooks && typeof hooks.rumorInjLine === 'function' ? hooks.rumorInjLine(r) : ''),
            flattenRumor: (r) => (hooks && typeof hooks.flattenRumor === 'function' ? hooks.flattenRumor(r) : null),
            dbgDump: () => (hooks && typeof hooks.dbgDump === 'function' ? hooks.dbgDump() : null),
            dbgErrors: (limit) => (hooks && typeof hooks.dbgErrors === 'function' ? hooks.dbgErrors(limit) : []),
            dbgErrorCount: () => (hooks && typeof hooks.dbgErrorCount === 'function' ? hooks.dbgErrorCount() : 0),
            dbgLastError: () => (hooks && typeof hooks.dbgLastError === 'function' ? hooks.dbgLastError() : null),
            errCaptureState: () => (hooks && typeof hooks.errCaptureState === 'function' ? hooks.errCaptureState() : { installed: false }),
            worldbookEntries: (env) => (hooks && typeof hooks.worldbookEntries === 'function' ? hooks.worldbookEntries(env) : []),
            worldbookKeys: (n) => (hooks && typeof hooks.worldbookKeys === 'function' ? hooks.worldbookKeys(n) : []),
            worldbookIsFttEntry: (e) => (hooks && typeof hooks.worldbookIsFttEntry === 'function' ? hooks.worldbookIsFttEntry(e) : false),
            worldbookLegacyEntryName: () => (hooks && typeof hooks.worldbookLegacyEntryName === 'function' ? hooks.worldbookLegacyEntryName() : ''),
            worldbookTotalBytes: (e) => (hooks && typeof hooks.worldbookTotalBytes === 'function' ? hooks.worldbookTotalBytes(e) : 0),
            worldbookMemoryTotal: () => (hooks && typeof hooks.worldbookMemoryTotal === 'function' ? hooks.worldbookMemoryTotal() : 0),
            worldbookSync: () => (hooks && typeof hooks.worldbookSync === 'function' ? hooks.worldbookSync() : false),
            worldbookSyncNow: () => (hooks && typeof hooks.worldbookSyncNow === 'function' ? hooks.worldbookSyncNow() : Promise.resolve(null)),
            worldbookSyncState: () => (hooks && typeof hooks.worldbookSyncState === 'function' ? hooks.worldbookSyncState() : null),
            worldbookNames: () => (hooks && typeof hooks.worldbookNames === 'function' ? hooks.worldbookNames() : []),
            refreshWorldbookNames: () => (hooks && typeof hooks.refreshWorldbookNames === 'function' ? hooks.refreshWorldbookNames() : Promise.resolve([])),
            // B8-6b+ 关联层机械维护（零 AI）
            relMaint: (opts) => (hooks && typeof hooks.relMaint === 'function' ? hooks.relMaint(opts || {}) : null),
            relMaintCounts: (m) => (hooks && typeof hooks.relMaintCounts === 'function' ? hooks.relMaintCounts(m) : null),
            relMaintTouched: (m) => (hooks && typeof hooks.relMaintTouched === 'function' ? hooks.relMaintTouched(m) : false),
            relMaintSummary: (m) => (hooks && typeof hooks.relMaintSummary === 'function' ? hooks.relMaintSummary(m) : ''),
            mergeRelMaint: (a, b) => (hooks && typeof hooks.mergeRelMaint === 'function' ? hooks.mergeRelMaint(a, b) : null),
            demoteRelLinkOrphans: () => (hooks && typeof hooks.demoteRelLinkOrphans === 'function' ? hooks.demoteRelLinkOrphans() : null),
            // B8-6c-1 相关组聚类修复基础设施 + 记忆修复管道（V1 `__FTT` 同名能力）
            groupSpecs: () => (hooks && typeof hooks.groupSpecs === 'function' ? hooks.groupSpecs() : null),
            groupSpec: (dimKey) => (hooks && typeof hooks.groupSpec === 'function' ? hooks.groupSpec(dimKey) : null),
            groupRelatedness: (spec) => (hooks && typeof hooks.groupRelatedness === 'function' ? hooks.groupRelatedness(spec) : null),
            groupClusters: (spec) => (hooks && typeof hooks.groupClusters === 'function' ? hooks.groupClusters(spec) : []),
            groupPick: (spec) => (hooks && typeof hooks.groupPick === 'function' ? hooks.groupPick(spec) : null),
            memoryMergeExact: () => (hooks && typeof hooks.memoryMergeExact === 'function' ? hooks.memoryMergeExact() : null),
            memoryRepairPrompt: (pick) => (hooks && typeof hooks.memoryRepairPrompt === 'function' ? hooks.memoryRepairPrompt(pick) : null),
            memoryRepairApply: (delta, pick) => (hooks && typeof hooks.memoryRepairApply === 'function' ? hooks.memoryRepairApply(delta, pick) : null),
            memoryRepair: (opts) => (hooks && typeof hooks.memoryRepair === 'function' ? hooks.memoryRepair(opts || {}) : Promise.resolve({ made: 0, error: 'no-hook' })),
            retargetRelRefs: (dim, fromIds, toId) => (hooks && typeof hooks.retargetRelRefs === 'function' ? hooks.retargetRelRefs(dim, fromIds, toId) : 0),
            // B8-6c-2 概念修复（V1 v1.139 聚类核对管道）+ 场景修复（V1 v1.89 全量重建管道）
            conceptMergeExact: () => (hooks && typeof hooks.conceptMergeExact === 'function' ? hooks.conceptMergeExact() : null),
            conceptRelatedness: () => (hooks && typeof hooks.conceptRelatedness === 'function' ? hooks.conceptRelatedness() : null),
            conceptClusters: () => (hooks && typeof hooks.conceptClusters === 'function' ? hooks.conceptClusters() : []),
            conceptPickClusters: () => (hooks && typeof hooks.conceptPickClusters === 'function' ? hooks.conceptPickClusters() : null),
            conceptRepairPrompt: (pick) => (hooks && typeof hooks.conceptRepairPrompt === 'function' ? hooks.conceptRepairPrompt(pick) : null),
            conceptRepairApply: (delta, pick) => (hooks && typeof hooks.conceptRepairApply === 'function' ? hooks.conceptRepairApply(delta, pick) : null),
            conceptRepair: (opts) => (hooks && typeof hooks.conceptRepair === 'function' ? hooks.conceptRepair(opts || {}) : Promise.resolve({ made: 0, error: 'no-hook' })),
            sceneRepairPrompt: () => (hooks && typeof hooks.sceneRepairPrompt === 'function' ? hooks.sceneRepairPrompt() : null),
            sceneRepairApply: (entries) => (hooks && typeof hooks.sceneRepairApply === 'function' ? hooks.sceneRepairApply(entries) : null),
            sceneRepair: (opts) => (hooks && typeof hooks.sceneRepair === 'function' ? hooks.sceneRepair(opts || {}) : Promise.resolve({ made: 0, error: 'no-hook' })),
            scenesUnionMergeAll: () => (hooks && typeof hooks.scenesUnionMergeAll === 'function' ? hooks.scenesUnionMergeAll() : 0),
            // B8-6c-3 物品修复（V1 v1.142 标签/名称聚类 + 低调用固定规则清理管道）
            isCurrencyItemName: (name, desc) => (hooks && typeof hooks.isCurrencyItemName === 'function' ? hooks.isCurrencyItemName(name, desc) : false),
            itemMergeExact: () => (hooks && typeof hooks.itemMergeExact === 'function' ? hooks.itemMergeExact() : null),
            itemLowUsesPurge: () => (hooks && typeof hooks.itemLowUsesPurge === 'function' ? hooks.itemLowUsesPurge() : null),
            itemRepairPrompt: (pick) => (hooks && typeof hooks.itemRepairPrompt === 'function' ? hooks.itemRepairPrompt(pick) : null),
            itemRepairApply: (delta, pick) => (hooks && typeof hooks.itemRepairApply === 'function' ? hooks.itemRepairApply(delta, pick) : null),
            itemRepair: (opts) => (hooks && typeof hooks.itemRepair === 'function' ? hooks.itemRepair(opts || {}) : Promise.resolve({ made: 0, error: 'no-hook' })),
            // B8-6c-3 角色档案修复（V1 v1.139 提取策略 + v1.152 出生必给 + v1.176 机械处理 + v1.205 已去世跳过）
            snapRepairFields: () => (hooks && typeof hooks.snapRepairFields === 'function' ? hooks.snapRepairFields() : null),
            snapRepairFieldMap: () => (hooks && typeof hooks.snapRepairFieldMap === 'function' ? hooks.snapRepairFieldMap() : null),
            snapshotAtomSize: (s) => (hooks && typeof hooks.snapshotAtomSize === 'function' ? hooks.snapshotAtomSize(s) : null),
            characterRepairQueue: () => (hooks && typeof hooks.characterRepairQueue === 'function' ? hooks.characterRepairQueue() : null),
            setSnapshotByPath: (s, path, val, o) => (hooks && typeof hooks.setSnapshotByPath === 'function' ? hooks.setSnapshotByPath(s, path, val, o) : null),
            characterRepairPrompt: (targets, o) => (hooks && typeof hooks.characterRepairPrompt === 'function' ? hooks.characterRepairPrompt(targets, o) : null),
            characterRepairApply: (delta, targets) => (hooks && typeof hooks.characterRepairApply === 'function' ? hooks.characterRepairApply(delta, targets) : null),
            characterRepair: (opts) => (hooks && typeof hooks.characterRepair === 'function' ? hooks.characterRepair(opts || {}) : Promise.resolve({ made: 0, error: 'no-hook' })),
            characterEvidencePack: (name, o) => (hooks && typeof hooks.characterEvidencePack === 'function' ? hooks.characterEvidencePack(name, o) : null),
            ensureSnapshotTags: (s) => (hooks && typeof hooks.ensureSnapshotTags === 'function' ? hooks.ensureSnapshotTags(s) : null),
            deriveSnapshotTags: (s, o) => (hooks && typeof hooks.deriveSnapshotTags === 'function' ? hooks.deriveSnapshotTags(s, o) : []),
            characterMechanicalPass: (o) => (hooks && typeof hooks.characterMechanicalPass === 'function' ? hooks.characterMechanicalPass(o) : null),
            correctSnapshotBirthDates: (o) => (hooks && typeof hooks.correctSnapshotBirthDates === 'function' ? hooks.correctSnapshotBirthDates(o) : null),
            // B8-6c-4 状态记录修复（V1 v1.158 匹配 → 机械清理 → AI 整理；v1.205 已去世固定规则）
            stateRepairFields: () => (hooks && typeof hooks.stateRepairFields === 'function' ? hooks.stateRepairFields() : null),
            stateCanonField: (f) => (hooks && typeof hooks.stateCanonField === 'function' ? hooks.stateCanonField(f) : ''),
            stateRepairRoster: () => (hooks && typeof hooks.stateRepairRoster === 'function' ? hooks.stateRepairRoster() : null),
            stateSubjectMatch: (s, roster, sim) => (hooks && typeof hooks.stateSubjectMatch === 'function' ? hooks.stateSubjectMatch(s, roster, sim) : ''),
            stateRepairMatch: (o) => (hooks && typeof hooks.stateRepairMatch === 'function' ? hooks.stateRepairMatch(o || {}) : null),
            stateRepairClean: () => (hooks && typeof hooks.stateRepairClean === 'function' ? hooks.stateRepairClean() : null),
            removeStatesOfDeceased: (o) => (hooks && typeof hooks.removeStatesOfDeceased === 'function' ? hooks.removeStatesOfDeceased(o || {}) : null),
            stateRepairTargets: (n) => (hooks && typeof hooks.stateRepairTargets === 'function' ? hooks.stateRepairTargets(n) : null),
            stateRepairPrompt: (pick) => (hooks && typeof hooks.stateRepairPrompt === 'function' ? hooks.stateRepairPrompt(pick) : null),
            stateRepairApply: (delta, pick) => (hooks && typeof hooks.stateRepairApply === 'function' ? hooks.stateRepairApply(delta, pick) : null),
            stateRepair: (opts) => (hooks && typeof hooks.stateRepair === 'function' ? hooks.stateRepair(opts || {}) : Promise.resolve({ made: 0, error: 'no-hook' })),
            // B8-6c-4 计划/悬念修复（V1 v1.140 悬念聚类核对 + v1.113 计划冗余合并）
            suspenseMergeExact: () => (hooks && typeof hooks.suspenseMergeExact === 'function' ? hooks.suspenseMergeExact() : null),
            planSuspRepairPrompt: (pick) => (hooks && typeof hooks.planSuspRepairPrompt === 'function' ? hooks.planSuspRepairPrompt(pick) : null),
            planSuspMergeApply: (delta) => (hooks && typeof hooks.planSuspMergeApply === 'function' ? hooks.planSuspMergeApply(delta) : null),
            suspenseRepairApply: (delta, pick) => (hooks && typeof hooks.suspenseRepairApply === 'function' ? hooks.suspenseRepairApply(delta, pick) : null),
            planSuspRepair: (opts) => (hooks && typeof hooks.planSuspRepair === 'function' ? hooks.planSuspRepair(opts || {}) : Promise.resolve({ made: 0, error: 'no-hook' })),
            // B8-7-a 情节总结（V1 v1.206 半自动早期情节聚合 + v1.203 手动多选合并）
            atomBodyChars: () => (hooks && typeof hooks.atomBodyChars === 'function' ? hooks.atomBodyChars() : 0),
            atomDateGrainKey: (d, g) => (hooks && typeof hooks.atomDateGrainKey === 'function' ? hooks.atomDateGrainKey(d, g) : ''),
            grainStartDateStr: (k) => (hooks && typeof hooks.grainStartDateStr === 'function' ? hooks.grainStartDateStr(k) : ''),
            atomCompactPlan: () => (hooks && typeof hooks.atomCompactPlan === 'function' ? hooks.atomCompactPlan() : null),
            atomGroupPlan: (grain) => (hooks && typeof hooks.atomGroupPlan === 'function' ? hooks.atomGroupPlan(grain) : null),
            buildAtomCompactPrompt: (chunk) => (hooks && typeof hooks.buildAtomCompactPrompt === 'function' ? hooks.buildAtomCompactPrompt(chunk) : null),
            compactGrainLabel: (grain, key) => (hooks && typeof hooks.compactGrainLabel === 'function' ? hooks.compactGrainLabel(grain, key) : ''),
            applyCompactGroup: (g, out, grain) => (hooks && typeof hooks.applyCompactGroup === 'function' ? hooks.applyCompactGroup(g, out, grain) : null),
            scheduleAtomCompact: () => (hooks && typeof hooks.scheduleAtomCompact === 'function' ? hooks.scheduleAtomCompact() : false),
            runAtomCompact: (opts) => (hooks && typeof hooks.runAtomCompact === 'function' ? hooks.runAtomCompact(opts || {}) : Promise.resolve({ ok: false, error: 'no-hook' })),
            atomMergeRange: (items) => (hooks && typeof hooks.atomMergeRange === 'function' ? hooks.atomMergeRange(items) : null),
            buildAtomMergePrompt: (items) => (hooks && typeof hooks.buildAtomMergePrompt === 'function' ? hooks.buildAtomMergePrompt(items) : null),
            parseAtomMergeResult: (resp) => (hooks && typeof hooks.parseAtomMergeResult === 'function' ? hooks.parseAtomMergeResult(resp) : null),
            atomMergeSummary: (ids, ai) => (hooks && typeof hooks.atomMergeSummary === 'function' ? hooks.atomMergeSummary(ids, ai) : null),
            runAtomMergeSummary: (ids, opts) => (hooks && typeof hooks.runAtomMergeSummary === 'function' ? hooks.runAtomMergeSummary(ids, opts || {}) : Promise.resolve({ made: 0, error: 'no-hook' })),
            // B8-7-a 情节分段总结（V1 v1.182 打包 → 分段 → `### 时间范围` 归档；只增不减、不注入）
            plotSegmentId: (e) => (hooks && typeof hooks.plotSegmentId === 'function' ? hooks.plotSegmentId(e) : ''),
            plotSegmentRange: (text) => (hooks && typeof hooks.plotSegmentRange === 'function' ? hooks.plotSegmentRange(text) : null),
            normalizePlotSegment: (e) => (hooks && typeof hooks.normalizePlotSegment === 'function' ? hooks.normalizePlotSegment(e) : null),
            normalizePlotSegmentLine: (raw) => (hooks && typeof hooks.normalizePlotSegmentLine === 'function' ? hooks.normalizePlotSegmentLine(raw) : null),
            normalizePlotSegmentLines: (raw, limit) => (hooks && typeof hooks.normalizePlotSegmentLines === 'function' ? hooks.normalizePlotSegmentLines(raw, limit) : []),
            parsePlotSegmentText: (text) => (hooks && typeof hooks.parsePlotSegmentText === 'function' ? hooks.parsePlotSegmentText(text) : []),
            plotSegmentsToText: (list) => (hooks && typeof hooks.plotSegmentsToText === 'function' ? hooks.plotSegmentsToText(list) : ''),
            plotSegmentTimeKey: (s) => (hooks && typeof hooks.plotSegmentTimeKey === 'function' ? hooks.plotSegmentTimeKey(s) : ''),
            plotSegmentTimeDesc: (a, b) => (hooks && typeof hooks.plotSegmentTimeDesc === 'function' ? hooks.plotSegmentTimeDesc(a, b) : 0),
            plotSegmentTimeAsc: (a, b) => (hooks && typeof hooks.plotSegmentTimeAsc === 'function' ? hooks.plotSegmentTimeAsc(a, b) : 0),
            sortPlotSegments: (list, mode) => (hooks && typeof hooks.sortPlotSegments === 'function' ? hooks.sortPlotSegments(list, mode) : []),
            plotSegmentBatchSize: () => (hooks && typeof hooks.plotSegmentBatchSize === 'function' ? hooks.plotSegmentBatchSize() : 0),
            plotSegmentAtomList: () => (hooks && typeof hooks.plotSegmentAtomList === 'function' ? hooks.plotSegmentAtomList() : []),
            plotSegmentCoveredIds: () => (hooks && typeof hooks.plotSegmentCoveredIds === 'function' ? hooks.plotSegmentCoveredIds() : []),
            plotSegmentBatchesFrom: (list, size) => (hooks && typeof hooks.plotSegmentBatchesFrom === 'function' ? hooks.plotSegmentBatchesFrom(list, size) : []),
            plotSegmentPlan: () => (hooks && typeof hooks.plotSegmentPlan === 'function' ? hooks.plotSegmentPlan() : null),
            plotSegmentPlanForIds: (ids) => (hooks && typeof hooks.plotSegmentPlanForIds === 'function' ? hooks.plotSegmentPlanForIds(ids) : null),
            buildPlotSegmentPrompt: (batch) => (hooks && typeof hooks.buildPlotSegmentPrompt === 'function' ? hooks.buildPlotSegmentPrompt(batch) : null),
            plotSegmentSameRange: (a, b) => (hooks && typeof hooks.plotSegmentSameRange === 'function' ? hooks.plotSegmentSameRange(a, b) : false),
            applyPlotSegmentResult: (batch, segments) => (hooks && typeof hooks.applyPlotSegmentResult === 'function' ? hooks.applyPlotSegmentResult(batch, segments) : null),
            runPlotSegmentSummary: (opts) => (hooks && typeof hooks.runPlotSegmentSummary === 'function' ? hooks.runPlotSegmentSummary(opts || {}) : Promise.resolve({ made: 0, error: 'no-hook' })),
            runPlotSegmentSummarySelected: (ids, opts) => (hooks && typeof hooks.runPlotSegmentSummarySelected === 'function' ? hooks.runPlotSegmentSummarySelected(ids, opts || {}) : Promise.resolve({ made: 0, error: 'no-hook' })),
            clearPlotSegments: () => (hooks && typeof hooks.clearPlotSegments === 'function' ? hooks.clearPlotSegments() : 0),
            deletePlotSegment: (id) => (hooks && typeof hooks.deletePlotSegment === 'function' ? hooks.deletePlotSegment(id) : 0),
            flattenPlotSegment: (item) => (hooks && typeof hooks.flattenPlotSegment === 'function' ? hooks.flattenPlotSegment(item) : null),
            atomSubState: () => (hooks && typeof hooks.atomSubState === 'function' ? hooks.atomSubState() : 'list'),
            setAtomSub: (v) => (hooks && typeof hooks.setAtomSub === 'function' ? hooks.setAtomSub(v) : 'list'),
            // B8-7-b 平行世界推演（weave）/ 平行事件推进（advance）/ 转正（promote）/ 清理（prune）
            weaveEnabled: () => (hooks && typeof hooks.weaveEnabled === 'function' ? hooks.weaveEnabled() : false),
            weavePassiveDue: (endF) => (hooks && typeof hooks.weavePassiveDue === 'function' ? hooks.weavePassiveDue(endF) : true),
            weaveInputSig: (start, end, floorsText) => (hooks && typeof hooks.weaveInputSig === 'function' ? hooks.weaveInputSig(start, end, floorsText) : ''),
            matchParallelsByKeywords: (keywords) => (hooks && typeof hooks.matchParallelsByKeywords === 'function' ? hooks.matchParallelsByKeywords(keywords) : []),
            scheduleParallelWeave: (fr, keywords) => (hooks && typeof hooks.scheduleParallelWeave === 'function' ? hooks.scheduleParallelWeave(fr, keywords) : null),
            runParallelWeave: (fr, opts) => (hooks && typeof hooks.runParallelWeave === 'function' ? hooks.runParallelWeave(fr, opts || {}) : Promise.resolve({ ok: false, error: 'no-hook' })),
            advanceContextSeed: (p) => (hooks && typeof hooks.advanceContextSeed === 'function' ? hooks.advanceContextSeed(p) : []),
            buildAdvanceContext: (targets) => (hooks && typeof hooks.buildAdvanceContext === 'function' ? hooks.buildAdvanceContext(targets) : ''),
            buildAdvancePrompt: (targets, memText) => (hooks && typeof hooks.buildAdvancePrompt === 'function' ? hooks.buildAdvancePrompt(targets, memText) : null),
            applyAdvanceUpdate: (p, u) => (hooks && typeof hooks.applyAdvanceUpdate === 'function' ? hooks.applyAdvanceUpdate(p, u) : false),
            runParallelAdvance: (opts) => (hooks && typeof hooks.runParallelAdvance === 'function' ? hooks.runParallelAdvance(opts || {}) : Promise.resolve({ ok: false, error: 'no-hook' })),
            promoteParallelEvent: (id, opts) => (hooks && typeof hooks.promoteParallelEvent === 'function' ? hooks.promoteParallelEvent(id, opts || {}) : { ok: false, reason: 'no-hook' }),
            prunePromotedParallels: () => (hooks && typeof hooks.prunePromotedParallels === 'function' ? hooks.prunePromotedParallels() : { removed: 0, kept: 0 }),
            setParallelLastKeywords: (list) => (hooks && typeof hooks.setParallelLastKeywords === 'function' ? hooks.setParallelLastKeywords(list) : []),
            parallelLastKeywords: () => (hooks && typeof hooks.parallelLastKeywords === 'function' ? hooks.parallelLastKeywords() : []),
            // P9d：被动调度关键词抽取 + 独立分组抽取 / 分组构造（V1 `jsExtractKeywords` / `runSummarySeparate` 同名能力）
            //   全部 `typeof` 守卫：未接线时返回空值（不抛异常、不建假动作）
            jsExtractKeywords: (text) => (hooks && typeof hooks.jsExtractKeywords === 'function' ? hooks.jsExtractKeywords(text) : []),
            runSummarySeparate: (text, fr, opts) => (hooks && typeof hooks.runSummarySeparate === 'function' ? hooks.runSummarySeparate(text, fr, opts || {}) : Promise.resolve([])),
            summaryDimGroups: (dims) => (hooks && typeof hooks.summaryDimGroups === 'function' ? hooks.summaryDimGroups(dims) : { enabled: [], rest: [] }),
            separateGroupingEnabled: () => (hooks && typeof hooks.separateGroupingEnabled === 'function' ? hooks.separateGroupingEnabled() : false),
            // B9-a 调试页：日志记录 / 读取 / 清空 / 统计（V1 `__FTT` 同名 `dbgLog` / `dbgGet` / `dbgClear`）
            //   注：本文件原约定为「只读快照、不暴露写数据能力」；此处按 V1 同名能力（用户要求 B9 对齐）显式放开
            //   `dbgLog` / `dbgClear` / `aboutClearCache` / `resetState` 四个**有意为之**的写入口，其余仍为只读。
            dbgLog: (kind, data) => (hooks && typeof hooks.dbgLog === 'function' ? hooks.dbgLog(kind, data) : false),
            dbgGet: () => (hooks && typeof hooks.dbgGet === 'function' ? hooks.dbgGet() : []),
            dbgLogGet: () => (hooks && typeof hooks.dbgLogGet === 'function' ? hooks.dbgLogGet() : []),
            dbgClear: () => (hooks && typeof hooks.dbgClear === 'function' ? hooks.dbgClear() : 0),
            debugLogStats: () => (hooks && typeof hooks.debugLogStats === 'function' ? hooks.debugLogStats() : null),
            // B9-a 关于页：版本清单读取（相对扩展目录）/ 状态 / 渲染 / 清缓存 / 候选地址 / 倒序 / 兜底
            aboutLoad: (force) => (hooks && typeof hooks.aboutLoad === 'function' ? hooks.aboutLoad(force === true) : Promise.resolve({ ok: false, reason: 'no-hook' })),
            aboutEnsureLoaded: () => (hooks && typeof hooks.aboutEnsureLoaded === 'function' ? hooks.aboutEnsureLoaded() : false),
            aboutState: () => (hooks && typeof hooks.aboutState === 'function' ? hooks.aboutState() : null),
            aboutData: () => (hooks && typeof hooks.aboutData === 'function' ? hooks.aboutData() : null),
            aboutHtml: () => (hooks && typeof hooks.aboutHtml === 'function' ? hooks.aboutHtml() : ''),
            aboutClearCache: () => (hooks && typeof hooks.aboutClearCache === 'function' ? hooks.aboutClearCache() : false),
            aboutCandidateUrls: () => (hooks && typeof hooks.aboutCandidateUrls === 'function' ? hooks.aboutCandidateUrls() : []),
            aboutSortDesc: (list) => (hooks && typeof hooks.aboutSortDesc === 'function' ? hooks.aboutSortDesc(list) : []),
            aboutFallback: () => (hooks && typeof hooks.aboutFallback === 'function' ? hooks.aboutFallback() : null),
            aboutJsonPaths: () => (hooks && typeof hooks.aboutJsonPaths === 'function' ? hooks.aboutJsonPaths() : []),
            aboutInfo: () => (hooks && typeof hooks.aboutInfo === 'function' ? hooks.aboutInfo() : null),
            aboutDirUrl: () => (hooks && typeof hooks.aboutDirUrl === 'function' ? hooks.aboutDirUrl() : ''),
            // B9-a 数据管理：清空当前角色记忆（V1 `resetState`；破坏性 —— 面板侧 `reset` 动作带二次确认）
            resetState: () => (hooks && typeof hooks.resetState === 'function' ? hooks.resetState() : Promise.resolve({ ok: false, reason: 'no-hook' })),
            // B9-b 关系表定位跳转 +「👥 选角色」（V1 `__FTT` 同名能力）
            //   注：`setRelPick` / `setRelFilter` / `setRelPickQuery` / `relJump` / `relGoto` 是**UI 导航态**写入口
            //   （不改数据、不落库）；与 V1 一致地暴露（V1 `__FTT` 亦导出 setRelPick/setRelFilter），其余为只读查询。
            relPickState: () => (hooks && typeof hooks.relPickState === 'function' ? hooks.relPickState() : null),
            setRelPick: (ref) => (hooks && typeof hooks.setRelPick === 'function' ? hooks.setRelPick(ref) : null),
            relFilterState: () => (hooks && typeof hooks.relFilterState === 'function' ? hooks.relFilterState() : null),
            setRelFilter: (dim, who, jump) => (hooks && typeof hooks.setRelFilter === 'function' ? hooks.setRelFilter(dim, who, jump) : null),
            relClearFilter: () => (hooks && typeof hooks.relClearFilter === 'function' ? hooks.relClearFilter() : null),
            relPickQuery: () => (hooks && typeof hooks.relPickQuery === 'function' ? hooks.relPickQuery() : ''),
            setRelPickQuery: (q) => (hooks && typeof hooks.setRelPickQuery === 'function' ? hooks.setRelPickQuery(q) : ''),
            relKnownNames: () => (hooks && typeof hooks.relKnownNames === 'function' ? hooks.relKnownNames() : []),
            relPickAppendRow: (dim, refId, name, opts) => (hooks && typeof hooks.relPickAppendRow === 'function' ? hooks.relPickAppendRow(dim, refId, name, opts || {}) : false),
            relPickPanelHtml: (dim, refId, editor) => (hooks && typeof hooks.relPickPanelHtml === 'function' ? hooks.relPickPanelHtml(dim, refId, editor === true || String(editor) === '1') : ''),
            relEntryTitle: (dim, it) => (hooks && typeof hooks.relEntryTitle === 'function' ? hooks.relEntryTitle(dim, it) : ''),
            relFindEntryId: (dim, raw) => (hooks && typeof hooks.relFindEntryId === 'function' ? hooks.relFindEntryId(dim, raw) : ''),
            relIsRelDim: (kind) => (hooks && typeof hooks.relIsRelDim === 'function' ? hooks.relIsRelDim(kind) : false),
            relDimLabelOf: (dim) => (hooks && typeof hooks.relDimLabelOf === 'function' ? hooks.relDimLabelOf(dim) : String(dim == null ? '' : dim)),
            relJump: (dim, id) => (hooks && typeof hooks.relJump === 'function' ? hooks.relJump(dim, id) : { ok: false, reason: 'no-hook' }),
            relGoto: (dim, id) => (hooks && typeof hooks.relGoto === 'function' ? hooks.relGoto(dim, id) : { ok: false, reason: 'no-hook' }),
            // B9-c 投喂标签自动分析（V1 `__FTT` 同名：latestAiFloorInfo / rxAnalyzeLatestText / rxNormTag /
            //   rxDedupeTagList / rxPushFeedTag / rxTagScanHtml）
            //   注：`rxPushFeedTag` / `setRxTagScan` 是**有意为之**的写入口（V1 `__FTT` 亦导出 `rxPushFeedTag`：
            //   收录进投喂白/黑名单并落盘；`setRxTagScan` 仅供诊断注入扫描结果），其余为只读查询。
            latestAiFloorInfo: () => (hooks && typeof hooks.latestAiFloorInfo === 'function' ? hooks.latestAiFloorInfo() : { text: '', floor: -1 }),
            rxAnalyzeLatestText: () => (hooks && typeof hooks.rxAnalyzeLatestText === 'function' ? hooks.rxAnalyzeLatestText() : null),
            rxNormTag: (raw) => (hooks && typeof hooks.rxNormTag === 'function' ? hooks.rxNormTag(raw) : ''),
            rxDedupeTagList: (list) => (hooks && typeof hooks.rxDedupeTagList === 'function' ? hooks.rxDedupeTagList(list) : []),
            rxPushFeedTag: (kind, raw) => (hooks && typeof hooks.rxPushFeedTag === 'function' ? hooks.rxPushFeedTag(kind, raw) : { added: false, reason: 'no-hook', tag: '', n: 0, other: false }),
            rxTagScanHtml: () => (hooks && typeof hooks.rxTagScanHtml === 'function' ? hooks.rxTagScanHtml() : ''),
            rxTagScan: () => (hooks && typeof hooks.rxTagScan === 'function' ? hooks.rxTagScan() : null),
            setRxTagScan: (v) => (hooks && typeof hooks.setRxTagScan === 'function' ? hooks.setRxTagScan(v) : null),
            rxFeedTagLists: () => (hooks && typeof hooks.rxFeedTagLists === 'function' ? hooks.rxFeedTagLists() : { white: [], black: [] }),
            feedScanAction: (a, p) => (hooks && typeof hooks.feedScanAction === 'function' ? hooks.feedScanAction(a, p || {}) : { ok: false, action: String(a || ''), title: '', text: '', note: 'no-hook' }),
            // B9-c 货币追踪（V1 `__FTT` 同名：normalizeTrackedRoles / trackedCurrencyRoles / isTrackedCurrencyOwner /
            //   knownCharacterNames / trackPickState / setTrackPick；V1 亦导出 add/remove/clear 三个写入口，此处同）
            normalizeTrackedRoles: (v) => (hooks && typeof hooks.normalizeTrackedRoles === 'function' ? hooks.normalizeTrackedRoles(v) : []),
            trackedCurrencyRoles: () => (hooks && typeof hooks.trackedCurrencyRoles === 'function' ? hooks.trackedCurrencyRoles() : []),
            isTrackedCurrencyOwner: (owner) => (hooks && typeof hooks.isTrackedCurrencyOwner === 'function' ? hooks.isTrackedCurrencyOwner(owner) : false),
            knownCharacterNames: () => (hooks && typeof hooks.knownCharacterNames === 'function' ? hooks.knownCharacterNames() : []),
            addTrackedCurrencyRole: (name) => (hooks && typeof hooks.addTrackedCurrencyRole === 'function' ? hooks.addTrackedCurrencyRole(name) : []),
            removeTrackedCurrencyRole: (name) => (hooks && typeof hooks.removeTrackedCurrencyRole === 'function' ? hooks.removeTrackedCurrencyRole(name) : []),
            clearTrackedCurrencyRoles: () => (hooks && typeof hooks.clearTrackedCurrencyRoles === 'function' ? hooks.clearTrackedCurrencyRoles() : 0),
            trackPickState: () => (hooks && typeof hooks.trackPickState === 'function' ? hooks.trackPickState() : false),
            setTrackPick: (v) => (hooks && typeof hooks.setTrackPick === 'function' ? hooks.setTrackPick(v) : false),
            defaultCurrencyOwner: () => (hooks && typeof hooks.defaultCurrencyOwner === 'function' ? hooks.defaultCurrencyOwner() : '主角'),
            t: (key, vars) => (hooks && typeof hooks.t === 'function' ? hooks.t(key, vars) : String(key == null ? '' : key)),
        });
        return true;
    } catch (e) {
        return false;
    }
}

export function uninstallDevtools() {
    try { if (globalThis.FTT && globalThis.FTT.version === VERSION) delete globalThis.FTT; return true; } catch (e) { return false; }
}
